name: GitHub-Profile-3D-Contrib

on:
  # 03:00 JST == 18:00 UTC
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          RANGE: "6 months"

      - name: Commit & Push (only if changed)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .

          # If nothing changed, exit successfully
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "generated"
          git push
